export const SET_CONFIG = 'SET_CONFIG';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SWITCH_AGENCY = 'SWITCH_AGENCY';
export const SET_TERMS_VISIBILITY = 'SET_TERMS_VISIBILITY';

export const SET_ALLOCATED_DETAILS = 'SET_ALLOCATED_DETAILS';
export const SET_UNALLOCATED_LIST = 'SET_UNALLOCATED_LIST';
export const SET_MANUAL_OVERRIDE_LIST = 'SET_MANUAL_OVERRIDE_LIST';
export const SET_MANUAL_OVERRIDE_DATE_FILTER = 'SET_MANUAL_OVERRIDE_DATE_FILTER';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_LOADED = 'SET_LOADED';

export const SET_OFFENDER_SEARCH_TEXT = 'SET_OFFENDER_SEARCH_TEXT';
export const SET_OFFENDER_SEARCH_ALLOCATION_STATUS = 'SET_OFFENDER_SEARCH_ALLOCATION_STATUS';
export const SET_OFFENDER_SEARCH_HOUSING_LOCATION = 'SET_OFFENDER_SEARCH_HOUSING_LOCATION';
export const SET_OFFENDER_SEARCH_LOCATIONS = 'SET_OFFENDER_SEARCH_LOCATIONS';
export const SET_OFFENDER_SEARCH_RESULTS = 'SET_OFFENDER_SEARCH_RESULTS';

export const SET_KEY_WORKER_SEARCH_TEXT = 'SET_KEY_WORKER_SEARCH_TEXT';
export const SET_KEY_WORKER_STATUS_FILTER = 'SET_KEY_WORKER_STATUS_FILTER';
export const SET_KEY_WORKER_STATUS = 'SET_KEY_WORKER_STATUS';
export const SET_KEY_WORKER_STATUS_CHANGE_BEHAVIOUR = 'SET_KEY_WORKER_STATUS_CHANGE_BEHAVIOUR';
export const SET_KEY_WORKER_CAPACITY = 'SET_KEY_WORKER_CAPACITY';
export const SET_KEY_WORKER_SEARCH_RESULTS_LIST = 'SET_KEY_WORKER_SEARCH_RESULTS_LIST';
export const SET_KEY_WORKER_ALLOCATION_LIST = 'SET_KEY_WORKER_ALLOCATION_LIST';
export const SET_ANNUAL_LEAVE_RETURN_DATE = 'SET_ANNUAL_LEAVE_RETURN_DATE';
export const SET_KEY_WORKER = 'SET_KEY_WORKER';
export const SET_KEY_WORKER_CHANGE_LIST = 'SET_KEY_WORKER_CHANGE_LIST';
export const SET_AVAILABLE_KEY_WORKER_LIST = 'SET_AVAILABLE_KEY_WORKER_LIST';
export const SET_ALLOCATION_HISTORY = 'SET_ALLOCATION_HISTORY';

export const SET_KEYWORKER_SETTINGS_CAPACITY = 'SET_KEYWORKER_SETTINGS_CAPACITY';
export const SET_KEYWORKER_SETTINGS_EXT_CAPACITY = 'SET_KEYWORKER_SETTINGS_EXT_CAPACITY';
export const SET_KEYWORKER_SETTINGS_SEQUENCE_FREQUENCY = 'SET_KEYWORKER_SETTINGS_SEQUENCE_FREQUENCY';
export const SET_KEYWORKER_SETTINGS_ALLOW_AUTO_ALLOCATION = 'SET_KEYWORKER_SETTINGS_ALLOW_AUTO_ALLOCATION';
export const SET_KEYWORKER_SETTINGS_SUPPORTED = 'SET_KEYWORKER_SETTINGS_SUPPORTED';
export const SET_KEYWORKER_SETTINGS_MIGRATED = 'SET_KEYWORKER_SETTINGS_MIGRATED';
export const SET_KEYWORKER_SETTINGS = 'SET_KEYWORKER_SETTINGS';

export const SET_USER_SEARCH_NAME_FILTER = 'SET_USER_SEARCH_NAME_FILTER';
export const SET_USER_SEARCH_ROLE_FILTER = 'SET_USER_SEARCH_ROLE_FILTER';
export const SET_USER_SEARCH_RESULTS_LIST = 'SET_USER_SEARCH_RESULTS_LIST';
export const SET_USER_SEARCH_ROLE_LIST = 'SET_USER_SEARCH_ROLE_LIST';
export const SET_USER_SEARCH_PAGINATION_PAGE_SIZE = 'SET_USER_SEARCH_PAGINATION_PAGE_SIZE';
export const SET_USER_SEARCH_PAGINATION_PAGE_NUMBER = 'SET_USER_SEARCH_PAGINATION_PAGE_NUMBER';
export const SET_USER_SEARCH_PAGINATION_TOTAL_RECORDS = 'SET_USER_SEARCH_PAGINATION_TOTAL_RECORDS';

export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';
export const RESET_VALIDATION_ERRORS = 'RESET_VALIDATION_ERRORS';

export const SET_MENU_OPEN = "SET_MENU_OPEN";
