export const SET_ALLOCATED_DETAILS = 'SET_ALLOCATED_DETAILS';
export const SET_UNALLOCATED_LIST = 'SET_UNALLOCATED_LIST';
export const SET_MANUAL_OVERRIDE_LIST = 'SET_MANUAL_OVERRIDE_LIST';
export const SET_MANUAL_OVERRIDE_DATE_FILTER = 'SET_MANUAL_OVERRIDE_DATE_FILTER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_ERROR = 'SET_ERROR';
