const keyworkerAllocations = [
  {
    bookingId: -24,
    offenderNo: 'Z0024ZZ',
    firstName: 'LUCIUS',
    lastName: 'FOX',
    staffId: -3,
    agencyId: 'LEI',
    prisonId: 'LEI',
    assigned: '2018-04-09T14:34:35.574',
    allocationType: 'A',
    internalLocationDesc: 'H-1',
    deallocOnly: false,
  },
  {
    bookingId: -33,
    offenderNo: 'A5577RS',
    firstName: 'HAROLD',
    lastName: 'LLOYD',
    staffId: -3,
    agencyId: 'LEI',
    prisonId: 'LEI',
    assigned: '2018-04-09T14:34:35.587',
    allocationType: 'A',
    internalLocationDesc: 'H-1',
    deallocOnly: false,
  },
  {
    bookingId: -34,
    offenderNo: 'A1178RS',
    firstName: 'FRED',
    lastName: 'QUIMBY',
    staffId: -3,
    agencyId: 'LEI',
    prisonId: 'LEI',
    assigned: '2018-04-09T14:34:35.595',
    allocationType: 'A',
    internalLocationDesc: 'H-1',
    deallocOnly: false,
  },
  {
    bookingId: -18,
    offenderNo: 'Z0018ZZ',
    firstName: 'NICK',
    lastName: 'TALBOT',
    staffId: -3,
    agencyId: 'LEI',
    prisonId: 'LEI',
    assigned: '2018-04-09T14:34:35.616',
    allocationType: 'A',
    internalLocationDesc: 'H-1',
    deallocOnly: false,
  },
  {
    bookingId: -19,
    offenderNo: 'Z0018ZT',
    firstName: 'DAVID',
    lastName: 'BOWIE',
    staffId: -3,
    agencyId: 'LPI',
    prisonId: 'LPI',
    assigned: '2018-04-10T12:00:00.000',
    allocationType: 'M',
    internalLocationDesc: 'LPI-A-1',
    deallocOnly: true,
  },
]

export default keyworkerAllocations
