---
# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: manage-key-workers

generic-service:
  image:
    repository: quay.io/hmpps/manage-key-workers
    tag: latest
    pullPolicy: IfNotPresent
    port: 3000

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping
  
  env:
    NODE_ENV: production
    MAINTAIN_ROLES_ENABLED: "true"
    KEYWORKER_PROFILE_STATS_ENABLED: "true"
    KEYWORKER_DASHBOARD_STATS_ENABLED: "true"
    REMOTE_AUTH_STRATEGY: "true"
    WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
    TOKENVERIFICATION_API_ENABLED: true
    REDIS_ENABLED: true

  ingress:
     enabled: true
     host: app-hostname.local
     tlsSecretName: manage-key-workers-cert
     v1_2_enabled: true
     v0_47_enabled: false
   
  namespace_secrets:
     manage-key-workers:
       API_CLIENT_ID: "API_CLIENT_ID"
       API_CLIENT_SECRET: "API_CLIENT_SECRET"
       API_SYSTEM_CLIENT_ID: "API_SYSTEM_CLIENT_ID"
       API_SYSTEM_CLIENT_SECRET: "API_SYSTEM_CLIENT_SECRET"
       APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
       GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"
       GOOGLE_TAG_MANAGER_ID: "GOOGLE_TAG_MANAGER_ID"
       SESSION_COOKIE_SECRET: "SESSION_COOKIE_SECRET"
     dps-redis:
       REDIS_HOST: "REDIS_HOST"
       REDIS_PASSWORD: "REDIS_PASSWORD"
