generic-service:
  replicaCount: 4
  env:
    HMPPS_COOKIE_NAME: hmpps-session-prod
    API_ENDPOINT_URL: https://prison-api.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-search.prison.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    HMPPS_MANAGE_USERS_API_URL: https://manage-users-api.hmpps.service.justice.gov.uk
    KEYWORKER_API_URL: https://keyworker-api.prison.service.justice.gov.uk
    NN_ENDPOINT_URL: https://digital.prison.service.justice.gov.uk/
    PRISON_STAFF_HUB_UI_URL: https://digital.prison.service.justice.gov.uk/
    TOKENVERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    SUPPORT_URL: https://support.hmpps.service.justice.gov.uk/
    COMPLEXITY_OF_NEED_URI: https://complexity-of-need.hmpps.service.justice.gov.uk
    PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "AGI,BZI,DHI,DWI,ESI,EWI,FHI,LNI,NHI,PFI,SDI,STI"
    MANAGE_KEY_WORKERS_URL: "https://manage-key-workers.service.justice.gov.uk/"
    HMPPS_COOKIE_DOMAIN: manage-key-workers.service.justice.gov.uk
    MAINTENANCE_MODE: false
    ENVIRONMENT_NAME: PRODUCTION
  ingress:
    host: manage-key-workers.service.justice.gov.uk
  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-prod
