# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generic-service:
  replicaCount: 2
  ingress:
    host: dev.manage-key-workers.service.justice.gov.uk
  env:
    API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    HMPPS_MANAGE_USERS_API_URL: https://manage-users-api-dev.hmpps.service.justice.gov.uk
    KEYWORKER_API_URL: https://keyworker-api-dev.prison.service.justice.gov.uk
    NN_ENDPOINT_URL: https://digital-dev.prison.service.justice.gov.uk/
    PRISON_STAFF_HUB_UI_URL: https://digital-dev.prison.service.justice.gov.uk/
    HMPPS_COOKIE_NAME: hmpps-session-dev
    TOKENVERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk/
    COMPLEXITY_OF_NEED_URI: https://complexity-of-need-staging.hmpps.service.justice.gov.uk
    PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "MDI,LEI"
    HMPPS_COOKIE_DOMAIN: dev.manage-key-workers.service.justice.gov.uk
    MANAGE_KEY_WORKERS_URL: "https://dev.manage-key-workers.service.justice.gov.uk/"
    MAINTENANCE_MODE: false

generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts-non-prod